// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using u22526162_HW01_API.Data;

#nullable disable

namespace u22526162_HW01_API.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("u22526162_HW01_API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductDescription = "A classic baseball cap with adjustable strap, made of breathable cotton. Perfect for casual wear and outdoor activities.",
                            ProductName = "Baseball Cap",
                            ProductPrice = 9.99m
                        },
                        new
                        {
                            ProductId = 2,
                            ProductDescription = "Lightweight and breathable running shoes with cushioned soles for enhanced comfort. Designed for maximum comfort and durability, making them ideal for long-distance running or daily workouts.",
                            ProductName = "Running Shoes",
                            ProductPrice = 99.99m
                        },
                        new
                        {
                            ProductId = 3,
                            ProductDescription = "Blue shirt with logo on front, made from breathable cotton.",
                            ProductName = "Blue Shirt",
                            ProductPrice = 49.99m
                        },
                        new
                        {
                            ProductId = 4,
                            ProductDescription = "HP Laptop with Intel i7 CPU, 16GB RAM, 256GB storage, OLED display",
                            ProductName = "Laptop",
                            ProductPrice = 999.99m
                        },
                        new
                        {
                            ProductId = 5,
                            ProductDescription = "Bluetooth mouse with RGB lights and wireless charging pad.",
                            ProductName = "Wireless Mouse",
                            ProductPrice = 79.99m
                        },
                        new
                        {
                            ProductId = 6,
                            ProductDescription = "High-capacity fast-charging power bank for mobile devices.",
                            ProductName = "Portable Power Bank",
                            ProductPrice = 59.86m
                        },
                        new
                        {
                            ProductId = 7,
                            ProductDescription = "Feature-packed smartwatch with heart rate monitoring, GPS, and Bluetooth connectivity.",
                            ProductName = "Smartwatch",
                            ProductPrice = 199.34m
                        },
                        new
                        {
                            ProductId = 8,
                            ProductDescription = "Over-ear wireless headphones with active noise cancellation and long battery life.",
                            ProductName = "Noise-Canceling Headphones",
                            ProductPrice = 149.99m
                        },
                        new
                        {
                            ProductId = 9,
                            ProductDescription = "Mechanical gaming keyboard with customizable RGB backlighting and programmable macro keys.",
                            ProductName = "Gaming Keyboard",
                            ProductPrice = 127.19m
                        },
                        new
                        {
                            ProductId = 10,
                            ProductDescription = "Water-resistant, lightweight camping tent suitable for 4 people, easy to set up and carry.",
                            ProductName = "Camping Tent",
                            ProductPrice = 190.01m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
